version: '3.8'

# Nacos with MySQL for production
# Usage: docker-compose -f docker-compose-nacos-mysql.yml up -d

services:
  # MySQL for Nacos
  nacos-mysql:
    image: mysql:5.7
    container_name: nacos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos_config
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos
    ports:
      - "3307:3306"
    volumes:
      - nacos_mysql_data:/var/lib/mysql
      - ./nacos-init.sql:/docker-entrypoint-initdb.d/nacos-init.sql
    networks:
      - quant-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nacos with MySQL backend
  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: quant-nacos
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: nacos-mysql
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
      JVM_XMS: 512m
      JVM_XMX: 512m
      JVM_XMN: 256m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - nacos_logs:/home/nacos/logs
    depends_on:
      nacos-mysql:
        condition: service_healthy
    networks:
      - quant-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  nacos_mysql_data:
  nacos_logs:

networks:
  quant-network:
    driver: bridge
